- name: teb-polite
  mobile:
    driver: nav2
    local_planner: teb
    inter_planner: polite
- name: teb-aggressive
  mobile:
    driver: nav2
    local_planner: teb
    inter_planner: aggressive
- name: rosnav-polite
  mobile:
    driver: nav2
    local_planner: rosnav
    inter_planner: polite
- name: rosnav-aggressive
  mobile:
    driver: nav2
    local_planner: rosnav
    inter_planner: aggressive
- name: cohan-polite
  mobile:
    driver: nav2
    local_planner: cohan
    inter_planner: polite
- name: cohan-aggressive
  mobile:
    driver: nav2
    local_planner: cohan
    inter_planner: aggressive
- name: teb-basic
  mobile:
    driver: nav2
    local_planner: teb
    inter_planner: bypass
- name: dwa-basic
  mobile:
    driver: nav2
    local_planner: dwa
    inter_planner: bypass
- name: dragon-basic
  mobile:
    driver: nav2
    local_planner: dragon
    inter_planner: bypass
- name: rosnav-basic
  mobile:
    driver: nav2
    local_planner: rosnav
    inter_planner: bypass
- name: applr-basic
  mobile:
    driver: nav2
    local_planner: applr
    inter_planner: bypass
- name: lflh-basic
  mobile:
    driver: nav2
    local_planner: lflh
    inter_planner: bypass
- name: trail-basic
  mobile:
    driver: nav2
    local_planner: trail
    inter_planner: bypass
- name: cohan-basic
  mobile:
    driver: nav2
    local_planner: cohan
    inter_planner: bypass
