- name: crowdnav
  mobile: drl
  mobile.planner: crowdnav
- name: drlvo
  mobile: drl
  mobile.planner: drlvo
- name: kdma
  mobile: drl
  mobile.planner: kdma
- name: rlrvo
  mobile: drl
  mobile.planner: rlrvo
- name: attngraph
  mobile: drl
  mobile.planner: attngraph
- name: nav2
  mobile: nav2
