name: showcase_planners
contestants:
  - name: teb-polite
    mobile:
      driver: nav2
      local_planner: teb
      inter_planner: polite
  - name: teb-aggressive
    mobile:
      driver: nav2
      local_planner: teb
      inter_planner: aggressive
  - name: dwa-basic
    mobile:
      driver: nav2
      local_planner: dwa
      inter_planner: bypass
  - name: rpp-replan-time
    mobile:
      driver: nav2
      local_planner: regulated_pure_pursuit
      inter_planner: navigate_w_replanning_time
