name: figure3_nightly_water
references: false
launch:
  sim: gazebo
  headless: true
  env.n: 1
stages:
- name: nightly_water_delivery
  map: hospital_1
  robot: jackal
  episodes: 1
  timeout: 300.0
  seed: 101
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: fig3_nightly_water_delivery
