name: figure8_hospital_door_dilemma
references: false
launch:
  sim: gazebo
  headless: true
  env.n: 1
stages:
- name: stage_top_door_direct
  map: hospital_1
  robot: jackal
  episodes: 3
  timeout: 300.0
  seed: 101
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: fig8_hospital_door_dilemma_direct

- name: stage_south_door_centerline
  map: hospital_1
  robot: jackal
  episodes: 3
  timeout: 300.0
  seed: 101
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: fig8_hospital_door_dilemma
