name: figure3a_ward_delivery
references: false
launch:
  sim: gazebo
  headless: true
  env.n: 1
stages:
- name: ward_bedside_delivery
  map: hospital_1
  robot: jackal
  episodes: 1
  timeout: 300.0
  seed: 101
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: fig3a_ward_bedside_delivery
