stages:
- name: hospital_stage_1
  map: hospital_1
  robot: jackal
  episodes: 5
  seed: 42
  tm_robots: random
  tm_obstacles: random
  timeout: 200s
  config:
    random:
      dynamic:
        min: 2
        max: 2
      static:
        min: 4
        max: 4

- name: hospital_stage_2
  map: hospital_1
  robot: jackal
  episodes: 5
  seed: 42
  tm_robots: random
  tm_obstacles: random
  timeout: 200s
  config:
    random:
      dynamic:
        min: 4
        max: 4
      static:
        min: 8
        max: 8

- name: hospital_stage_3
  map: hospital_1
  robot: jackal
  episodes: 5
  seed: 42
  tm_robots: random
  tm_obstacles: random
  timeout: 200s
  config:
    random:
      dynamic:
        min: 6
        max: 6
      static:
        min: 12
        max: 12

- name: hospital_stage_4
  map: hospital_1
  robot: jackal
  episodes: 5
  seed: 42
  tm_robots: random
  tm_obstacles: random
  timeout: 200s
  config:
    random:
      dynamic:
        min: 8
        max: 8
      static:
        min: 16
        max: 16

- name: hospital_stage_5
  map: hospital_1
  robot: jackal
  episodes: 5
  seed: 42
  tm_robots: random
  tm_obstacles: random
  timeout: 200s
  config:
    random:
      dynamic:
        min: 10
        max: 10
      static:
        min: 20
        max: 20
