stages:
# ── Jackal ───────────────────────────────────────────────────────────────────
- name: hospital_stage_1_jackal
  map: hospital_1
  robot: jackal
  episodes: 1
  seed: 235687490
  tm_robots: random
  tm_obstacles: random
  timeout: 100s
  config:
    random:
      dynamic:
        min: 2
        max: 2

- name: hospital_stage_2_jackal
  map: hospital_1
  robot: jackal
  episodes: 1
  seed: 106593478
  tm_robots: random
  tm_obstacles: random
  timeout: 100s
  config:
    random:
      dynamic:
        min: 3
        max: 3

- name: hospital_stage_3_jackal
  map: hospital_1
  robot: jackal
  episodes: 1
  seed: 92856374
  tm_robots: random
  tm_obstacles: random
  timeout: 100s
  config:
    random:
      dynamic:
        min: 4
        max: 4

- name: hospital_stage_4_jackal
  map: hospital_1
  robot: jackal
  episodes: 1
  seed: 3465978
  tm_robots: random
  tm_obstacles: random
  timeout: 100s
  config:
    random:
      dynamic:
        min: 6
        max: 6

- name: hospital_stage_5_jackal
  map: hospital_1
  robot: jackal
  episodes: 1
  seed: 9744867
  tm_robots: random
  tm_obstacles: random
  timeout: 100s
  config:
    random:
      dynamic:
        min: 8
        max: 8