launch:
  robot.mobile.deadline: 30

stages:
  - name: quicktest_map_empty
    map: map_empty
    robot: auto
    tm_robots: scenario
    tm_obstacles: scenario
    episodes: 5
    config:
      scenario:
        file: quicktest
