name: suite_empty_crucible
references: false
launch:
  sim: gazebo
  headless: true
  env.n: 1
stages:
- name: stage_crucible
  map: map_empty
  robot: jackal
  episodes: 5
  timeout: 120.0
  seed: 101
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: empty_crucible
