references: false
stages:
- name: stage_hospital_1
  map: hospital_1
  robot: jackal
  episodes: 1
  timeout: 140.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: s01_head_on

- name: stage_hospital_2
  map: hospital_2
  robot: jackal
  episodes: 1
  timeout: 140.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: s01_head_on

- name: stage_office_1
  map: office_1
  robot: jackal
  episodes: 1
  timeout: 180.0
  tm_robots: scenario
  tm_obstacles: scenario
  config:
    scenario:
      file: office_s01_long_hallway_commute
